Pull C++14 settings from Melodic moveit_core subpackage
TOTG uses `std::make_unique()`, causing these errors:

    [...]/src/moveit_core/trajectory_processing/src/time_optimal_trajectory_generation.cpp:220:34: error: ‘make_unique’ is not a member of ‘std’